package:
  name: open-spiel
  version: "1.5.0.1"

source:
  git: git@github.com:google-deepmind/open_spiel.git
  target_directory: open_spiel

requirements:
  # note that there is no build section
  build:
    - cmake
    - make
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - pkg-config
    - wget
    - setuptools
    - wheel
    - git
  host:
    - pip
    - python >=3.9
  run:
    - python >=3.9
    - pip >=20.0.2
    - attrs >=19.3.0
    - absl-py >=0.10.0
    - numpy >=1.21.5
    - scipy >=1.10.1
    - ml-collections >=0.1.1

tests:
  - python:
      imports:
        - pyspiel

about:
  homepage: https://github.com/google-deepmind/open_spiel
  license: Apache-2.0
  license_file: open_spiel/LICENSE
  summary: A Framework for Reinforcement Learning in Games
  description: |
    OpenSpiel is a collection of environments and algorithms for research in general reinforcement learning and search/planning in games.
