context:
  version: "1.3.2"

package:
  name: btop
  version: ${{ version }}

source:
  url: https://github.com/aristocratos/btop/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 331d18488b1dc7f06cfa12cff909230816a24c57790ba3e8224b117e3f0ae03e

build:
  skip: ["win"]
  number: 0
  script:
    - mkdir build
    - if: osx
      then: |
        export CXXFLAGS="$CXXFLAGS -D_LIBCPP_DISABLE_AVAILABILITY"
    - if: win 
      then: |
        cmake -B build %CMAKE_ARGS% -DCMAKE_EXE_LINKER_FLAGS="-ldl" -GNinja %SRC_DIR%
        ninja install -C build
      else: |
        cmake -B build $CMAKE_ARGS -DCMAKE_EXE_LINKER_FLAGS="-ldl" -GNinja $SRC_DIR  
        ninja install -C build

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - pkg-config
    - cmake
    - ninja


tests:
  - script:
      - btop --help
